toml-version = "v1.0.0"

[files]
include = ["**/*.toml"]

[format]
[format.rules]
array-bracket-space-width = 0
array-comma-space-width = 1
date-time-delimiter = "T"
indent-style = "tab"
indent-sub-tables = false
# indent-table-key-values = false
indent-width = 2
inline-table-brace-space-width = 1
inline-table-comma-space-width = 1
# key-value-equal-alignment = false
# key-value-equal-space-width = 1
line-ending = "lf"
line-width = 80
trailing-comment-alignment = false
trailing-comment-space-width = 2

[lint]
[lint.rules]
dotted-keys-out-of-order = "warn"
key-empty = "warn"
tables-out-of-order = "warn"

[lsp]
code-action.enabled = true
completion.enabled = true
document-link.enabled = true
formatting.enabled = true
goto-declaration.enabled = true
goto-definition.enabled = true
goto-type-definition.enabled = true
hover.enabled = true
workspace-diagnostic.enabled = true
