[package]
name = "fp-macros"
version = "0.1.0"
edition = "2024"
license = "BlueOak-1.0.0"
keywords = ["macro", "proc-macro", "types", "procedural"]
categories = ["encoding"]
workspace = "../"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["extra-traits", "full"] }
