[package]
name = "fp-library"
version = "0.0.20"
edition = "2024"
description = "A functional programming library for Rust featuring your favourite higher-kinded types and type classes."
readme = "../README.md"
repository = "https://github.com/nothingnesses/rust-fp-library"
license = "BlueOak-1.0.0"
keywords = ["functional", "higher-kinded", "types"]
categories = ["algorithms", "data-structures", "rust-patterns"]
workspace = "../"

[features]
default = ["v1"]
v1 = []
v2 = []

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"
